// Do not edit this file. generated by getcommands.ts
const value = {
    MODES: {
        cmdNo: 0,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    MODEG: {
        cmdNo: 1,
        p1: '-',
        p2: '-',
        res: 'mode',
        extension: [
            '-'
        ]
    },
    PUD: {
        cmdNo: 2,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    READ: {
        cmdNo: 3,
        p1: '-',
        p2: '-',
        res: 'level',
        extension: [
            '-'
        ]
    },
    WRITE: {
        cmdNo: 4,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    PWM: {
        cmdNo: 5,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    PRS: {
        cmdNo: 6,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    PFS: {
        cmdNo: 7,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    SERVO: {
        cmdNo: 8,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    WDOG: {
        cmdNo: 9,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    BR1: {
        cmdNo: 10,
        p1: '-',
        p2: '-',
        res: 'bits',
        extension: [
            '-'
        ]
    },
    BR2: {
        cmdNo: 11,
        p1: '-',
        p2: '-',
        res: 'bits',
        extension: [
            '-'
        ]
    },
    BC1: {
        cmdNo: 12,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    BC2: {
        cmdNo: 13,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    BS1: {
        cmdNo: 14,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    BS2: {
        cmdNo: 15,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    TICK: {
        cmdNo: 16,
        p1: '-',
        p2: '-',
        res: 'tick',
        extension: [
            '-'
        ]
    },
    HWVER: {
        cmdNo: 17,
        p1: '-',
        p2: '-',
        res: 'version',
        extension: [
            '-'
        ]
    },
    NO: {
        cmdNo: 18,
        p1: '-',
        p2: '-',
        res: 'handle',
        extension: [
            '-'
        ]
    },
    NB: {
        cmdNo: 19,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    NP: {
        cmdNo: 20,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    NC: {
        cmdNo: 21,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    PRG: {
        cmdNo: 22,
        p1: '-',
        p2: '-',
        res: 'range',
        extension: [
            '-'
        ]
    },
    PFG: {
        cmdNo: 23,
        p1: '-',
        p2: '-',
        res: 'frequency',
        extension: [
            '-'
        ]
    },
    PRRG: {
        cmdNo: 24,
        p1: '-',
        p2: '-',
        res: 'real range',
        extension: [
            '-'
        ]
    },
    HELP: {
        cmdNo: 25,
        p1: '-',
        p2: '-',
        res: 'N/A',
        extension: [
            'N/A'
        ]
    },
    PIGPV: {
        cmdNo: 26,
        p1: '-',
        p2: '-',
        res: 'version',
        extension: [
            '-'
        ]
    },
    WVCLR: {
        cmdNo: 27,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    WVAG: {
        cmdNo: 28,
        p1: '-',
        p2: '-',
        res: 'wave pulses',
        extension: [
            '-'
        ]
    },
    WVAS: {
        cmdNo: 29,
        p1: '-',
        p2: '-',
        res: 'wave pulses',
        extension: [
            '-'
        ]
    },
    WVBSY: {
        cmdNo: 32,
        p1: '-',
        p2: '-',
        res: 'busy (1) or not busy (0)',
        extension: [
            '-'
        ]
    },
    WVHLT: {
        cmdNo: 33,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    WVSM: {
        cmdNo: 34,
        p1: '-',
        p2: '-',
        res: 'wave micros\nwave micros - high\nwave micros - max',
        extension: [
            '-'
        ]
    },
    WVSP: {
        cmdNo: 35,
        p1: '-',
        p2: '-',
        res: 'wave pulses\nwave pulses - high\nwave pulses - max',
        extension: [
            '-'
        ]
    },
    WVSC: {
        cmdNo: 36,
        p1: '-',
        p2: '-',
        res: 'wave DMA CBs\nwave DMA CBs - high\nwave DMA CBs - max',
        extension: [
            '-'
        ]
    },
    TRIG: {
        cmdNo: 37,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    PROC: {
        cmdNo: 38,
        p1: '-',
        p2: '-',
        res: 'script id',
        extension: [
            '-'
        ]
    },
    PROCD: {
        cmdNo: 39,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    PROCR: {
        cmdNo: 40,
        p1: '-',
        p2: '-',
        res: 'script status',
        extension: [
            '-'
        ]
    },
    PROCS: {
        cmdNo: 41,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    SLRO: {
        cmdNo: 42,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    SLR: {
        cmdNo: 43,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t data[X]'
        ]
    },
    SLRC: {
        cmdNo: 44,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    PROCP: {
        cmdNo: 45,
        p1: '-',
        p2: '-',
        res: '44',
        extension: [
            'uint32_t script_status',
            'uint32_t pars[10]'
        ]
    },
    MICS: {
        cmdNo: 46,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    MILS: {
        cmdNo: 47,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    PARSE: {
        cmdNo: 48,
        p1: '-',
        p2: '-',
        res: 'N/A',
        extension: [
            '-'
        ]
    },
    WVCRE: {
        cmdNo: 49,
        p1: '-',
        p2: '-',
        res: 'wave id',
        extension: [
            '-'
        ]
    },
    WVDEL: {
        cmdNo: 50,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    WVTX: {
        cmdNo: 51,
        p1: '-',
        p2: '-',
        res: 'wave DMA CBs',
        extension: [
            '-'
        ]
    },
    WVTXR: {
        cmdNo: 52,
        p1: '-',
        p2: '-',
        res: 'wave DMA CBs',
        extension: [
            '-'
        ]
    },
    WVNEW: {
        cmdNo: 53,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    I2CO: {
        cmdNo: 54,
        p1: '-',
        p2: '-',
        res: 'handle',
        extension: [
            '-'
        ]
    },
    I2CC: {
        cmdNo: 55,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    I2CRD: {
        cmdNo: 56,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t data[X]'
        ]
    },
    I2CWD: {
        cmdNo: 57,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    I2CWQ: {
        cmdNo: 58,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    I2CRS: {
        cmdNo: 59,
        p1: '-',
        p2: '-',
        res: 'byte value',
        extension: [
            '-'
        ]
    },
    I2CWS: {
        cmdNo: 60,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    I2CRB: {
        cmdNo: 61,
        p1: '-',
        p2: '-',
        res: 'byte value',
        extension: [
            '-'
        ]
    },
    I2CWB: {
        cmdNo: 62,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    I2CRW: {
        cmdNo: 63,
        p1: '-',
        p2: '-',
        res: 'word value',
        extension: [
            '-'
        ]
    },
    I2CWW: {
        cmdNo: 64,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    I2CRK: {
        cmdNo: 65,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    I2CWK: {
        cmdNo: 66,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    I2CRI: {
        cmdNo: 67,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t data[X]'
        ]
    },
    I2CWI: {
        cmdNo: 68,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    I2CPC: {
        cmdNo: 69,
        p1: '-',
        p2: '-',
        res: 'word value',
        extension: [
            '-'
        ]
    },
    I2CPK: {
        cmdNo: 70,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t data[X]'
        ]
    },
    SPIO: {
        cmdNo: 71,
        p1: '-',
        p2: '-',
        res: 'handle',
        extension: [
            '-'
        ]
    },
    SPIC: {
        cmdNo: 72,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    SPIR: {
        cmdNo: 73,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t data[X]'
        ]
    },
    SPIW: {
        cmdNo: 74,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    SPIX: {
        cmdNo: 75,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t data[X]'
        ]
    },
    SERO: {
        cmdNo: 76,
        p1: '-',
        p2: '-',
        res: 'handle',
        extension: [
            '-'
        ]
    },
    SERC: {
        cmdNo: 77,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    SERRB: {
        cmdNo: 78,
        p1: '-',
        p2: '-',
        res: 'byte value',
        extension: [
            '-'
        ]
    },
    SERWB: {
        cmdNo: 79,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    SERR: {
        cmdNo: 80,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t data[X]'
        ]
    },
    SERW: {
        cmdNo: 81,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    SERDA: {
        cmdNo: 82,
        p1: '-',
        p2: '-',
        res: 'data ready count',
        extension: [
            '-'
        ]
    },
    GDC: {
        cmdNo: 83,
        p1: '-',
        p2: '-',
        res: 'dutycycle',
        extension: [
            '-'
        ]
    },
    GPW: {
        cmdNo: 84,
        p1: '-',
        p2: '-',
        res: 'pulsewidth',
        extension: [
            '-'
        ]
    },
    HC: {
        cmdNo: 85,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    HP: {
        cmdNo: 86,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    CF1: {
        cmdNo: 87,
        p1: '-',
        p2: '-',
        res: 'value',
        extension: [
            '-'
        ]
    },
    CF2: {
        cmdNo: 88,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t retBuf[X]'
        ]
    },
    BI2CC: {
        cmdNo: 89,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    BI2CO: {
        cmdNo: 90,
        p1: '-',
        p2: '-',
        res: 'handle',
        extension: [
            '-'
        ]
    },
    BI2CZ: {
        cmdNo: 91,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t data[X]'
        ]
    },
    I2CZ: {
        cmdNo: 92,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t data[X]'
        ]
    },
    WVCHA: {
        cmdNo: 93,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    SLRI: {
        cmdNo: 94,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    CGI: {
        cmdNo: 95,
        p1: '-',
        p2: '-',
        res: 'config',
        extension: [
            '-'
        ]
    },
    CSI: {
        cmdNo: 96,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    FG: {
        cmdNo: 97,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    FN: {
        cmdNo: 98,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    NOIB: {
        cmdNo: 99,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    WVTXM: {
        cmdNo: 100,
        p1: '-',
        p2: '-',
        res: 'wave DMA CBs',
        extension: [
            '-'
        ]
    },
    WVTAT: {
        cmdNo: 101,
        p1: '-',
        p2: '-',
        res: 'wave id',
        extension: [
            '-'
        ]
    },
    PADS: {
        cmdNo: 102,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    PADG: {
        cmdNo: 103,
        p1: '-',
        p2: '-',
        res: 'strength',
        extension: [
            '-'
        ]
    },
    FO: {
        cmdNo: 104,
        p1: '-',
        p2: '-',
        res: 'handle',
        extension: [
            '-'
        ]
    },
    FC: {
        cmdNo: 105,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    FR: {
        cmdNo: 106,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t data[X]'
        ]
    },
    FW: {
        cmdNo: 107,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    FS: {
        cmdNo: 108,
        p1: '-',
        p2: '-',
        res: 'position',
        extension: [
            '-'
        ]
    },
    FL: {
        cmdNo: 109,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t filenames[X]'
        ]
    },
    SHELL: {
        cmdNo: 110,
        p1: '-',
        p2: '-',
        res: 'exit status',
        extension: [
            '-'
        ]
    },
    BSPIC: {
        cmdNo: 111,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    BSPIO: {
        cmdNo: 112,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    BSPIX: {
        cmdNo: 113,
        p1: '-',
        p2: '-',
        res: 'X',
        extension: [
            'uint8_t data[X]'
        ]
    },
    BSCX: {
        cmdNo: 114,
        p1: '-',
        p2: '-',
        res: 'X+4',
        extension: [
            'uint32_t status',
            'uint8_t data[X]'
        ]
    },
    EVM: {
        cmdNo: 115,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    EVT: {
        cmdNo: 116,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    },
    PROCU: {
        cmdNo: 117,
        p1: '-',
        p2: '-',
        res: '0',
        extension: [
            '-'
        ]
    }
} as const
export default value
